### ISSUE TITLE
Server does not update.

### ISSUE THREAD

**Issue by romerocox** [fpaezf/CS2-server-manager#2]
Hello!

I'm probably doing something wrong, but:

When I hit 'update all servers' SteamCMD says they're all up-to-date but it doesn't actually update the servers... as I get the 'Client out of date' message when trying to connect to the game.

![image](https://github.com/user-attachments/assets/715e5c58-b186-4051-8447-057f04135690)
Servers starts as expected, no issues there, so I believe the path is correct? 

![image](https://github.com/user-attachments/assets/cd5853f2-a5c2-4c1e-981a-fa23c70c0c7b)

**Comment by fpaezf** [comment]
Update YOUR client.

**Comment by romerocox** [comment]
Just so you're aware, my cliente was up-to-date. I was able to login to my other test servers. Apparently, steamcmd is not respecting the force directory install. 

I'm no longer using this application but I thought you'd like to know.
thank you
